objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Budget__c/fields/BudgetArea__c.field-meta.xml
<CustomField>
    <fullName>BudgetArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Area__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/BudgetSub_Area__c.field-meta.xml
<CustomField>
    <fullName>BudgetSub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sub_Area__c.Area__c</field>
            <operation>equals</operation>
            <valueField>$Source.BudgetArea__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawl</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub Area</label>
    <nameField>
        <label>Sub Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subareas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Subareas</relationshipLabel>
    <relationshipName>Subareas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/BudgetListHandler.cls
public class BudgetListHandler {
    
    @AuraEnabled
    public static List<Budget__c> getallBudgets()
    {
        //List<Budget__c> ng = new List<Budget__c>{};
        list<Budget__c> budgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c];
        return budgets;
    }
    
    @AuraEnabled
    public static List<Budget__c> handleChanges(string selectedkey)
    {
        List<Budget__c> budget = new List<Budget__c>{};
        switch on selectedkey{
            when 'All Budgets'{
                list<Budget__c> allbudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c];
       			budget = allbudgets;
            }
            when 'Upcoming Budgets'{
                list<Budget__c> upcomingBudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Start_Date__c > TODAY];
       			budget = upcomingBudgets;
            }
            when 'Amount'{
                list<Budget__c> AmountBudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Budget_Amount__c > 20];
       			budget = AmountBudgets;
            }
            when 'Closed'{
                list<Budget__c> ClosedBudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where End_Date__c < TODAY];
       			budget = ClosedBudgets;
            }
            
            
        }
        
        return budget;
    }
    
    @AuraEnabled
    public static List<Budget__c> handleSearch(string pick, string input)
    {
        List<Budget__c> totalBud = new list<Budget__c>{};
        switch on pick{
            when 'Status'{
                list<Budget__c> statusBudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Status__c LIKE :input+'%'];
       			totalBud = statusBudgets;
            }       
        }
        return totalBud;
    }
    
    @AuraEnabled
    public static List<Area__c> getAreaPicklist()
    {
        List<Area__c> areas = [select Name from Area__c];
        return areas;
    }
    
	@AuraEnabled
    public static List<Sub_Area__c> getSubAreas()
    {
        List<Sub_Area__c> subareas = [select Name from Sub_Area__c];
        
        return subareas;
    }
    
    @AuraEnabled
    public static List<Budget__c> getBudgetsByArea(string area)
    {
        LIst<Budget__c> areabudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where BudgetArea__r.Name=:area ]; 
        return areabudgets;
    }
    
    @AuraEnabled
    public static list<Budget__c> getBgtByAmount(string key, integer amount)
    {
        List<Budget__c> getAmountbudgets = new List<Budget__c>{};
        switch on key {
            
            when 'Equal to'{
                getAmountbudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Budget_Amount__c =:amount];
                //system.debug(getAmountbudgets);
            }
            when 'Greater Than'{
                getAmountbudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Budget_Amount__c > :amount];
            }
            when 'Smaller Than'{
                getAmountbudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Budget_Amount__c < :amount];
            }
            
        }
        return getAmountbudgets;
    }
    
    @AuraEnabled
    public static list<Budget__c> getBgtAmount2(string key, integer start, integer endd)
    {
        List<Budget__c> getAmountbudgets = new List<Budget__c>{};
        getAmountbudgets = [select Name,Title__c,BudgetArea__r.Name,BudgetSub_Area__r.Name,Start_Date__c,End_Date__c,Budget_Amount__c,Status__c from Budget__c where Budget_Amount__c > :start AND Budget_Amount__c <:endd ];
        return getAmountbudgets;
    }

    }